version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - neepco-lms-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm start"

  email-worker:
    build:
      context: ./backend
    container_name: email-worker
    depends_on:
      - redis
    env_file: .env
    command: ["npm", "run", "start-emailWorker"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:3000"
      PORT: 3001 

volumes:
  neepco-lms-data:
